Repository stolostron/backplane-operator, pull requests merged in 2022-03, with the labels that each got.

#123 Add PlacementDecisions to console-clusterrole
  pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#121 adding agg roles for managed serviceaccount
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-managed-serviceaccount.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-managed-serviceaccount.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-managed-serviceaccount.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-managed-serviceaccount.yaml
Labels: lgtm, approved, dco-signoff: yes

#125 Correct official MCE component name
  pkg/templates/charts/toggle/console-mce/Chart.yaml
Labels: lgtm, approved, dco-signoff: yes

#127 update go dependencies
  go.mod
  go.sum
  pkg/foundation/cluster_manager.go
Labels: lgtm, approved, dco-signoff: yes

#128 Chart polling (managed service account)
  .github/workflows/regenerate-charts.yml
  Makefile.dev
  hack/bundle-automation/chart-requirements.txt
  hack/bundle-automation/chart-values/managed-serviceaccount/values.yaml
  hack/bundle-automation/charts-config.yaml
  hack/bundle-automation/generate-charts.py
  pkg/templates/charts/toggle/managed-serviceaccount/templates/deployment.yaml
  pkg/templates/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml
Labels: lgtm, approved, dco-signoff: yes

#129 redoing chart link to use https instead of ssh
  hack/bundle-automation/charts-config.yaml
Labels: lgtm, approved, dco-signoff: yes

#130 updating script to run with python3
  hack/bundle-automation/generate-charts.py
Labels: lgtm, approved, dco-signoff: yes

#132 update rbac for addonplacementscores and import controller
  config/rbac/role.yaml
  controllers/backplaneconfig_controller.go
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-clc.yaml
  pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
Labels: lgtm, approved, dco-signoff: yes

#133 Add cluster-proxy-addon CRD
  config/rbac/role.yaml
  controllers/backplaneconfig_controller.go
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-clc.yaml
  pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-clc.yaml
Labels: lgtm, approved, dco-signoff: yes

#136 removing clusterrole and binding tests, updating cr & b naming to not…
  controllers/backplaneconfig_controller_test.go
  hack/bundle-automation/generate-charts.py
Labels: lgtm, approved, dco-signoff: yes

#138 Allow console-mce to be toggled off in 4.10
  controllers/backplaneconfig_controller.go
Labels: lgtm, approved, dco-signoff: yes

#140 no-op
  README.md
Labels: approved, dco-signoff: yes

#141 Pin Hive to mce-2.0
  hack/bundle-automation/config.yaml
Labels: lgtm, approved, dco-signoff: yes

#126 Onboard Hypershift
  api/v1/multiclusterengine_methods.go
  bundle.Dockerfile
  bundle/manifests/multicluster-engine.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  controllers/backplaneconfig_controller.go
  controllers/toggle_components.go
  pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
  pkg/templates/charts/toggle/hypershift/Chart.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-clusterrolebinding.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-serviceaccount.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment-deployment.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment_clusterrole.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment_clusterrolebinding.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment_leader_election_role.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment_leader_election_role_binding.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment_serviceaccount.yaml
  pkg/templates/charts/toggle/hypershift/values.yaml
  pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
  pkg/toggle/toggle.go
  pkg/utils/utils.go
  test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
  test/function_tests/run_tests.sh
Labels: lgtm, approved, dco-signoff: yes

#142 No-op
  README.md
Labels: approved, ok-to-test

#144 Ensures bundled CSV is up to date
  bundle/manifests/multicluster-engine.clusterserviceversion.yaml
  pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#145 Move component list to overrides and remove restrictions
  api/v1/multiclusterengine_methods.go
  api/v1/multiclusterengine_types.go
  api/v1/multiclusterengine_webhook.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/multicluster-engine.clusterserviceversion.yaml
  bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
  config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
  controllers/backplaneconfig_controller_test.go
  test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
Labels: lgtm, approved, dco-signoff: yes

#146 Ensure ReplicaCount of 1
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#147 No-op
  README.md
Labels: approved, dco-signoff: yes

#148 Add subscription.operators.coreos.com to console-clusterrole
  bundle.Dockerfile
  bundle/manifests/multicluster-engine.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  controllers/backplaneconfig_controller.go
  pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#149 Onboard HyperShift Configmap
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
  pkg/templates/charts/toggle/hypershift/values.yaml
  pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#150 No-op
  README.md
Labels: lgtm, approved, dco-signoff: yes

#154 Collapse repeat components in spec to one
  controllers/backplaneconfig_controller.go
  controllers/backplaneconfig_controller_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, dco-signoff: yes

#157 Proceed with deploying other components if one fails
  controllers/backplaneconfig_controller.go
  controllers/toggle_components.go
  pkg/toggle/toggle.go
Labels: lgtm, approved, dco-signoff: yes

#158 Add static override to change assisted installer namespace
  api/v1/multiclusterengine_types.go
  api/v1/multiclusterengine_webhook.go
  bundle/manifests/multicluster-engine.clusterserviceversion.yaml
  bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
  config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
  config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
  controllers/toggle_components.go
  pkg/rendering/renderer.go
Labels: lgtm, approved, dco-signoff: yes

#159 Change ReplicaCount to 1 for HyperShiftDeployment
  pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#161 CRD adds new printer column
  pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Labels: lgtm, approved, dco-signoff: yes

#162 Add new printer column and update CRD with hypershift:release-4.10
  pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Labels: lgtm, approved, dco-signoff: yes

#163 Rename ConfigMap
  pkg/templates/charts/toggle/console-mce/templates/console-configmap.yaml
  pkg/templates/charts/toggle/console-mce/templates/console-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#165 add lease rbac for work-manger addon agent in ocp 311 case
  pkg/templates/charts/toggle/server-foundation/templates/clusterrole-foundation-agent.yaml
Labels: lgtm, approved, dco-signoff: yes

#166 Added missing HOSTING print column for HypershiftDeployment
  pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Labels: lgtm, approved, dco-signoff: yes

#167 add lease permission
  pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#170 update the renamed fields
  pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Labels: lgtm, approved, dco-signoff: yes
