Repository stolostron/backplane-operator, pull requests merged in 2024-12, with the labels that each got.

#1094 Remove lingering hypershift-preview resources on upgrade
  controllers/backplaneconfig_controller.go
  controllers/toggle_components_test.go
Labels: lgtm, do-not-merge/hold, approved, dco-signoff: yes

#1115 remove hypershift-preview resources
  controllers/backplaneconfig_controller.go
  controllers/toggle_components_test.go
Labels: lgtm, approved, dco-signoff: yes

#1113 [ACM-15739] added addon check before addon components
  .gitignore
  controllers/backplaneconfig_controller.go
  hack/scripts/dev-update-image-references.py
Labels: lgtm, approved, dco-signoff: yes

#1131 Fixed ClusterManager bug
  controllers/backplaneconfig_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1126 remove limit for server foundation components
  pkg/templates/charts/hosting/server-foundation/templates/managedcluster-import-deployment.yaml
  pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
  pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
  pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
  pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
  pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
  pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
  pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
  pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
Labels: lgtm, approved, dco-signoff: yes

#1148 Remove cluster-api image reference from hypershift addon chart
  pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
Labels: lgtm, approved, dco-signoff: yes

#1149 [ACM-15665] Added CAPA component to charts config
  config/rbac/role.yaml
  hack/bundle-automation/charts-config.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/Chart.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-controller-manager-deployment.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-controller-manager-serviceaccount.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-leader-elect-role-role.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-leader-elect-rolebinding-rolebinding.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-manager-bootstrap-credentials-secret.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-manager-role-clusterrole.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-manager-rolebinding-clusterrolebinding.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-metrics-service-service.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-system-namespace.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-validating-webhook-configuration-validatingwebhookconfiguration.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-webhook-service-service.yaml
  pkg/templates/charts/toggle/cluster-api-provider-aws/values.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsclusters.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmachines.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/eksconfigs.bootstrap.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/rosaclusters.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/rosacontrolplanes.controlplane.cluster.x-k8s.io.yaml
  pkg/templates/crds/cluster-api-provider-aws/rosamachinepools.infrastructure.cluster.x-k8s.io.yaml
  pkg/templates/rbac_gen.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1150 [ACM-15739] Added addon check before addon components
  controllers/backplaneconfig_controller.go
Labels: lgtm, approved, dco-signoff: yes
